# 2)მომხარებელს შემოატანინეთ ორი რიცხვი, შემდეგ ამ 2 რიცხვს შორის ჩაატარეთ ყველა არითმეტიკული ოპერატორი (+, -, *, /, **)
number = int(input("enter the first number: "))
number1 = int(input("enter the second number: "))
print(number+number1)
print(number-number1)
print(number*number1)
print(number/number1)
print(number//number1)
print(number**number1)